package community.community.model;

public class UserAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.ID
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.ACCOUNT_ID
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.NAME
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.PASSWORD
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.EMAIL
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.SEX
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.GMT_CREATE
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.GMT_MODIFIED
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useraccount.avatar_url
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.ID
     *
     * @return the value of useraccount.ID
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.ID
     *
     * @param id the value for useraccount.ID
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.ACCOUNT_ID
     *
     * @return the value of useraccount.ACCOUNT_ID
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.ACCOUNT_ID
     *
     * @param accountId the value for useraccount.ACCOUNT_ID
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.NAME
     *
     * @return the value of useraccount.NAME
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.NAME
     *
     * @param name the value for useraccount.NAME
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.PASSWORD
     *
     * @return the value of useraccount.PASSWORD
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.PASSWORD
     *
     * @param password the value for useraccount.PASSWORD
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.EMAIL
     *
     * @return the value of useraccount.EMAIL
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.EMAIL
     *
     * @param email the value for useraccount.EMAIL
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.SEX
     *
     * @return the value of useraccount.SEX
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.SEX
     *
     * @param sex the value for useraccount.SEX
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.GMT_CREATE
     *
     * @return the value of useraccount.GMT_CREATE
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.GMT_CREATE
     *
     * @param gmtCreate the value for useraccount.GMT_CREATE
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.GMT_MODIFIED
     *
     * @return the value of useraccount.GMT_MODIFIED
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.GMT_MODIFIED
     *
     * @param gmtModified the value for useraccount.GMT_MODIFIED
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useraccount.avatar_url
     *
     * @return the value of useraccount.avatar_url
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useraccount.avatar_url
     *
     * @param avatarUrl the value for useraccount.avatar_url
     *
     * @mbg.generated Wed Jul 14 16:56:25 CST 2021
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}