CREATE TABLE useraccount
(
    ID int AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACCOUNT_ID VARCHAR(100),
    NAME VARCHAR(50),
   	PASSWORD VARCHAR(36),
   	EMAIL VARCHAR(60),
   	SEX VARCHAR(10),
    GMT_CREATE BIGINT,
    GMT_MODIFIED BIGINT,
    avatar_url VARCHAR(100)
);